### PR TITLE
Fix console URL in docker quickstart

### PR DESCRIPTION
**Pull request by slonopotamus**

### CODE REVIEW

**Review by arxdsilva — APPROVED** [review]

**Comment by slonopotamus** [comment]
I wonder what does this silent closing of a PR means.

**Comment by seanpackham** [comment]
Hi @slonopotamus it's a small change that still needed some edits. If you don't mind updating your changes to `[http://127.0.0.1:7351](127.0.0.1:7351):` I can get them merged.

**Comment by slonopotamus** [comment]
> `(127.0.0.1:7351)`

This part is wrong. Modern browsers attempt to use HTTPS, that's why we need explicit `http://`.

**Comment by slonopotamus** [comment]
No, really, I just tried walking through that quickstart and it doesn't work.

**Comment by seanpackham** [comment]
My mistake, Markdown syntax got me again, I meant to write it as `[127.0.0.1:7351](http://127.0.0.1:7351)` to not display the `http://`. Is that ok?

**Comment by slonopotamus** [comment]
Done

**Pull request merged**
